name: minato-env
channels:
  - defaults
dependencies:
  - python=3.8  # Ensure this matches your project's Python version
  - pip
  - pip:
    - streamlit
    - streamlit-ace
    - openai
    - pandas
    - numpy
    - matplotlib
    - plotly
    - html5lib
    - json5
    - subprocess32  # Note: subprocess32 is for Python < 3.5; consider using the standard library subprocess if using Python 3.5+
    - pytimeparse
    - shutilwhich
    - stat-utils
    - pickle-mixin
    - pathlib2  # Note: pathlib is part of the standard library in Python 3.5+
    - GitPython
    - regex
    - requests
    - lxml
    - pytest
    - aiohttp
    - pygame
    - PyQt5
    - PyOpenGL
    - selenium
    - PyAutoGUI
    - python-dotenv
